-- ============================================================
-- D1 Data Import Script for Arman Law Firm
-- ============================================================
-- This file is generated by scripts/migrate-to-d1.ts
-- when you provide a source-data.json file.
-- 
-- To import data:
-- 1. Create migrations/source-data.json with your data
-- 2. Run: npx tsx scripts/migrate-to-d1.ts
-- 3. Run: npx wrangler d1 execute wb-data_bs_armanlawfirm --remote --file=./migrations/data-import.sql
-- ============================================================

-- No data to import (placeholder file)
-- Add your INSERT statements below or generate them from source-data.json

SELECT 1;
